
services:
  - type: web
    name: harambee-housing
    env: php
    buildCommand: composer install
    startCommand: vendor/bin/heroku-php-apache2 .
    envVars:
      - key: PORT
        value: 8000
      - key: PHP_VERSION
        value: 8.0
    buildFilter:
      paths:
      - "**/*.php"
      - "**/*.json"
      - "**/*.html"
      - "**/*.css"
      - "**/*.js"
      ignoredPaths:
      - "pyproject.toml"
