services:
  - type: web
    name: harambe-student
    env: docker
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PHP_VERSION
        value: 8.0
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        sync: false